fail_on_violations: true

stylelint:
  config_file: build/.stylelintrc

scss:
  enabled: false

jshint:
  enabled: false

eslint:
  config_file: js/.eslintrc.json
  ignore_file: .houndignore

ruby:
  enabled: false
