# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
destination:      ./_gh_pages
exclude:          [".editorconfig", ".gitignore", ".ruby-version", "bower.json", "composer.json", "CONTRIBUTING.md", "LICENSE", "Makefile", "package.json", "node_modules", "README.md", "less"]
port:             9001

# Custom vars
repo:             https://github.com/twbs/bootstrap
download:         https://github.com/twbs/bootstrap/archive/v3.0.0-rc1.zip
download_dist:    https://github.com/twbs/bootstrap/archive/v3.0.0-rc1-dist.zip
